export default {
	extends: ["@commitlint/config-conventional"],
	rules: {
		"ai-attribution-forbidden": [2, "always"],
		"type-enum": [
			2,
			"always",
			[
				"feat",
				"fix",
				"docs",
				"style",
				"refactor",
				"perf",
				"test",
				"build",
				"ci",
				"chore",
				"revert",
			],
		],
	},
	plugins: [
		{
			rules: {
				"ai-attribution-forbidden": ({ raw }) => {
					const forbiddenPatterns = [
						/generated with claude/i,
						/claude code/i,
						/\ud83e\udd16.*claude/i,
						/co-authored-by:.*claude/i,
						/generated by ai/i,
						/ai-generated/i,
						/generated with.*ai/i,
					];

					const hasForbiddenPattern = forbiddenPatterns.some((pattern) =>
						pattern.test(raw),
					);

					return [
						!hasForbiddenPattern,
						hasForbiddenPattern
							? "Commit messages must not contain AI attribution. Please remove any references to AI generation."
							: "",
					];
				},
			},
		},
	],
};